---
- name: Restart lighttpd
  ansible.builtin.service:
    name: lighttpd
    state: restarted
  become: true
  become_user: root

- name: Reboot required
  ansible.builtin.reboot:
    reboot_timeout: 300
  become: true
  become_user: root

- name: Kill timelapse.py
  ansible.builtin.copy:
    content: "Please die now"
    dest: "/tmp/timelapse.kill"
    mode: "0644"
    owner: root
    group: root
  become: true
  become_user: root
